### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by alexanderpaolini** [discord-rose/discord-rose#4]
When a bot is started without any code on the worker, the logs are spammed with
 ```xl
Cluster 0 | Closed with code 0
Cluster 0 | Started
```

About a second in, `(node:4007) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 KILL listeners added to [Cluster]. Use emitter.setMaxListeners() to increase limit
(Use "node --trace-warnings ..." to show where the warning was created)` is logged.

### master.js:
```js
const { Master } = require('discord-rose')
const path = require('path')

const master = new Master(path.resolve(__dirname, 'worker.js'), {
  token: "BOT-TOKEN-HERE"
});

master.start();
```
### worker.js:
```js

```
---
This was found by starting a master before any code was written.

**Comment by jpbberry** [comment]
This is definitely not a major issue. I'll look into adding a fail safe for constant restarts, or some type of wait before a restart. Easiest way to solve this is to have actual running code as a worker.

**Comment by alexanderpaolini** [comment]
Closed because stale.

**Comment by BowsiePup** [comment]
Still an issue tho
