### ISSUE TITLE
Wiki for using commands instead of tell is wrong.

### ISSUE THREAD

**Issue by BowsiePup** [discord-rose/discord-rose#8]
[https://github.com/discord-rose/discord-rose/wiki/Using-Clusters#using-commands-instead-of-tell](https://github.com/discord-rose/discord-rose/wiki/Using-Clusters#using-commands-instead-of-tell) is wrong the code block indicates there only being 2 parameters passed in (data & respond). In reality there are 3 (cluster, data & respond). Fix it

```js
const thing = 'abc'

master.handlers.on('GET_THING', (cluster, data, respond) => {
  if (data === true) return respond(thing) // responds to the event with this data
  respond({ error: 'Error message' }) // can also throw errors back on the worker
})
```

**Comment by BowsiePup** [comment]
Also shown here: [https://github.com/discord-rose/discord-rose/blob/master/src/clustering/master/Master.ts#L45](https://github.com/discord-rose/discord-rose/blob/master/src/clustering/master/Master.ts#L45)

**Comment by jpbberry** [comment]
Just fixed!
